### ISSUE TITLE
Error when running gulp-rework: no 'slice' method

### ISSUE THREAD

**Issue by OliverJAsh** [sindresorhus/gulp-rework#11]
``` js
gulp.task('css', function () {
    gulp.src('./src/css/main.css')
        .pipe(rework())
        .pipe(gulp.dest('./target/css'));
});
```

Error:

```
❯ ./node_modules/.bin/gulp css
[11:14:53] Using gulpfile ~/Development/bright-north-site-v4/Gulpfile.js
[11:14:53] Starting 'css'...
[11:14:53] 'css' errored after 6.28 ms
[11:14:53] TypeError: Cannot call method 'slice' of undefined
    at match (/Users/Oliver/Development/bright-north-site-v4/node_modules/rework/node_modules/css/lib/parse/index.js:129:15)
    at whitespace (/Users/Oliver/Development/bright-north-site-v4/node_modules/rework/node_modules/css/lib/parse/index.js:138:5)
    at rules (/Users/Oliver/Development/bright-north-site-v4/node_modules/rework/node_modules/css/lib/parse/index.js:109:5)
    at stylesheet (/Users/Oliver/Development/bright-north-site-v4/node_modules/rework/node_modules/css/lib/parse/index.js:81:16)
    at module.exports (/Users/Oliver/Development/bright-north-site-v4/node_modules/rework/node_modules/css/lib/parse/index.js:558:20)
    at rework (/Users/Oliver/Development/bright-north-site-v4/node_modules/rework/index.js:26:21)
    at Gulp.<anonymous> (/Users/Oliver/Development/bright-north-site-v4/Gulpfile.js:19:15)
    at module.exports (/Users/Oliver/Development/bright-north-site-v4/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/Oliver/Development/bright-north-site-v4/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/Oliver/Development/bright-north-site-v4/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
```

**Comment by james-peel** [comment]
Did you find a solution for this @OliverJAsh ?
